### ISSUE TITLE
Clarify irregular plural rule

### ISSUE THREAD

**Issue by Tyriar** [sindresorhus/irregular-plurals#3]
> Irregular plurals are nouns that cannot be made plural by adding an "s" or "es" to the end

torpedo->torpedoes and veto->vetoes is in the list but according to the above they do not meet the criteria for being an irregular plural. There are other examples that some sites say are irregular like watch->watches. Clarifying the readme for the exact requirements would be good.

**Comment by sindresorhus** [comment]
Agreed.

Does anyone know a good explanation?

**Comment by Tyriar** [comment]
I think something along the lines of this should do it http://web2.uvcs.uvic.ca/elc/studyzone/330/grammar/plural.htm - I can put a pull request together if you want to assign this to me.

**Comment by sindresorhus** [comment]
> I can put a pull request together if you want to assign this to me.

:+1: That would be rad :)

**Comment by Qix-** [comment]
Yeah there are pretty well defined rules for `s` vs `es` grammar. A PR would be great.
