### ISSUE TITLE
`Torpedoes` is included erroneously

### ISSUE THREAD

**Issue by iankronquist** [sindresorhus/irregular-plurals#9]
In the README you define the rule `irregular plurals are nouns that cannot be made plural by adding an "s" or "es" to the end`, which I contest, but that's covered in other issues. In any case, torpedoes is merely torpedo+es.

**Comment by Qix-** [comment]
:+1: I saw that too.

**Comment by Qix-** [comment]
Fixed!

**Comment by ersel** [comment]
This fix seems to have broken the `plur` test suite. 

https://github.com/sindresorhus/plur/blob/master/test.js#L25
